name: git rev-parse HEAD

on: pull_request

jobs:
  git-rev-parse-head:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git rev-parse HEAD github.event.pull_request.commits
        run: git rev-parse HEAD~${{ github.event.pull_request.commits }}

