---
name: head_ref

on:
  pull_request:
    branches: [master, main]

jobs:

  head_ref:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo github.repository_owner || true
          echo ${{ github.repository_owner }} || true
          echo github.repository || true
          echo ${{ github.repository }} || true
          echo env github.event.pull_request.number || true
          echo ${{ github.event.pull_request.number }} || true
          echo "gh api -H "Accept: application/vnd.github.v3+json" /repos/OWNER/REPO/pulls/PULL_NUMBER/commits":
          gh api -H "Accept: application/vnd.github.v3+json" /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits | jq || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: github.event.pull_request.head.ref
        run: |
          echo github.event.pull_request.head.ref:
          echo ${{ github.event.pull_request.head.ref }}
          echo github.base_ref:
          echo ${{ github.base_ref }}
          echo ######################################################################################################
          echo git log --pretty=%B:
          git log --pretty=%B || true
          echo ######################################################################################################
          echo git log $(git merge-base master branch-name)..branch-name:
          git log $(git merge-base ${{ github.base_ref }} ${{ github.event.pull_request.head.ref }})..${{ github.event.pull_request.head.ref }} || true
          echo ######################################################################################################
          echo git log -${{ github.event.pull_request.commits }} --pretty=format:%s:
          git log -${{ github.event.pull_request.commits }} --pretty=format:%s || true
          echo ######################################################################################################
          echo git log --pretty=format:%s:
          git log --pretty=format:%s || true
          echo ######################################################################################################
          echo git log github.event.pull_request.head.ref github.base_ref:
          git log ${{ github.event.pull_request.head.ref }}..${{ github.base_ref }} || true
          echo ######################################################################################################
          echo git log github.base_ref github.event.pull_request.head.ref:
          git log ${{ github.base_ref }} ${{ github.event.pull_request.head.ref }} || true
          echo ######################################################################################################
          echo git github.base_ref github.event.pull_request.head.ref:
          git rev-list ${{ github.base_ref }} ${{ github.event.pull_request.head.ref }} || true
          echo ######################################################################################################
          echo git rev-list origin..HEAD:
          git rev-list origin..HEAD || true
          echo ######################################################################################################
          echo git rev-list HEAD ^origin:
          git rev-list HEAD ^origin || true
          echo ######################################################################################################
          echo git log github.event.pull_request.base.sha..github.event.pull_request.head.sha --pretty=format:%s 
          git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:%s || true
          echo ######################################################################################################
          echo git rev-parse github.event.pull_request.base.sha^github.event.pull_request.commits
          git rev-parse ${{ github.event.pull_request.base.sha }}^${{ github.event.pull_request.commits }} || true
          echo ######################################################################################################
          echo git rev-parse github.event.pull_request.head.sha^github.event.pull_request.commits
          git rev-parse ${{ github.event.pull_request.head.sha }}^${{ github.event.pull_request.commits }} || true
          echo ######################################################################################################
